Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the Auto Scaling Group

Resources:

  ChildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: InlinePolicyForSsmPutParameter
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ssm:PutParameter"
                Resource: "*"

  ChildInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: ChildRole

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: '3'
      MaxSize: '3'
      DesiredCapacity: '3'
      VPCZoneIdentifier:
        Ref: SubnetIds
      Tags:
        - Key: Name
          Value: ChildEC2Instance
          PropagateAtLaunch: true

  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: "ami-087c4d241dd19276d"
      InstanceType: "t3.micro"
      IamInstanceProfile: !Ref ChildInstanceProfile
      KeyName: "key-pair_default"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          instance_id=$(ec2-metadata -i | cut -d " " -f 2)
          aws ssm put-parameter --name $instance_id --value "Hey from child instance" --type "String" --overwrite
#      SecurityGroupIds: ["sg-0a6c4c517135364fb"] # TODO: is this needed? what about autoscaling group?

Outputs:
  AutoScalingGroupName:
    Description: The name of the Auto Scaling Group
    Value: !Ref MyAutoScalingGroup