AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to launch the child EC2 instances.'

Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the Auto Scaling Group
  AMIId:
    Type: String
    Description: AMI ID for the instances
  InstanceType:
    Type: String
    Description: EC2 instance type
  NumberOfInstances:
    Type: Number
    Description: Number of EC2 instances to launch

Resources:
  ChildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: SsmPutParameter
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ssm:PutParameter"
                Resource: "*"

  ChildInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: ChildRole

  ChildAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref ChildLaunchConfiguration
      MinSize: !Ref NumberOfInstances
      MaxSize: !Ref NumberOfInstances
      DesiredCapacity: !Ref NumberOfInstances
      VPCZoneIdentifier:
        Ref: SubnetIds
      Tags:
        - Key: Name
          Value: ChildInstance
          PropagateAtLaunch: true

  ChildLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref ChildInstanceProfile
      UserData:
        Fn::Base64: !Sub |
${BootScriptContent} # this is replaced at runtime
#      SecurityGroupIds: ["sg-0a6c4c517135364fb"] # TODO: is this needed?

Outputs:
  ChildASGName:
    Description: The name of the Auto Scaling Group
    Value: !Ref ChildAutoScalingGroup